{{- if (.Values.midpoint.schema.enabled) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "midpoint.configmap.schema" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: midpoint
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
{{ (.Files.Glob "config/objects/schema/*.xsd").AsConfig | indent 2 }}
{{- end }}
