name: '[Support] Synchronize team members in the .env file'
on:
  schedule:
    # Daily
    - cron: '0 5 * * *'
permissions:
  repository-projects: write

jobs:
  sync-support-teams:
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.INALOGY_BOT_TOKEN }}
          fetch-depth: 1
      - name: Load .env file
        uses: xom9ikk/dotenv@v2
        with:
          path: .github/workflows/
      - name: Updating members of the Inalogy team
        run: |
          TEAM_MEMBERS=$(curl --request GET \
          --url https://api.github.com/orgs/inalogy/teams/developers/members?per_page=100 \
          --header 'authorization: Bearer ${{ secrets.INALOGY_BOT_TOKEN }}' \
          --header 'content-type: application/json' \
          | jq 'sort_by(.login)|map(.login)|join(",")')
          TEAM_MEMBERS='['${TEAM_MEMBERS//','/'","'}']'
          if [ $TEAM_MEMBERS != $INALOGY_TEAM ]; then
            echo "Replacing $INALOGY_TEAM for $TEAM_MEMBERS"
            sed -i "s|INALOGY_TEAM=.*$|INALOGY_TEAM='${TEAM_MEMBERS}'|g" .github/workflows/.env
            git config user.name "inalogy-bot"
            git config user.email "inalogy-bot@inalogy.com"
            git commit -s -m"[inalogy-bot] Updating Inalogy team members" .github/workflows/.env 
            git push
          else
            echo "INALOGY_TEAM is updated and nothing should be done"
          fi